version: '3.4'
services:
  api:
    container_name: benkyoukai.api
    build:
      context: ./Benkyoukai.Api/
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - ASPNETCORE_URLS=http://+:6000
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - db
    networks:
      - front-tier
      - back-tier
    restart: on-failure
  db: 
    container_name: benkyoukai.db
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=benkyoukai
      - POSTGRES_USER=postgres
      - POSTGRES_DB=benkyoukaidb
    volumes:
      - benkyoukaidev:/var/lib/postgresql/data
    networks:
      - back-tier
    restart: always

networks:
  front-tier:
  back-tier:

volumes:
  benkyoukaidev:
