version: '3.4'
services:
  db: 
    container_name: benkyoukai.db
    image: ninjaz/study.db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=benkyoukai
      - POSTGRES_USER=postgres
      - POSTGRES_DB=benkyoukaidb
    volumes:
      - benkyoukaidev:/var/lib/postgresql/data
    networks:
      - back-tier
    restart: always

networks:
  back-tier:

volumes:
  benkyoukaidev:
