version: '3.4'
services:
  web:
    container_name: portfiolio.site
    image: ninjaz/portfolio
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - front-tier
  api:
    container_name: benkyoukai.api
    image: ninjaz/benkyoukai:latest
    ports:
      - "6000:6000"
      - "6001:6001"
    environment:
      - ASPNETCORE_URLS=http://+:6000;https://+:6001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=benkyoukai
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on: 
      - db
    networks:
      - front-tier
      - back-tier
    restart: on-failure
  db: 
    container_name: benkyoukai.db
    image: postgres:alpine
    ports:
      - "6003:5432"
    environment:
      - POSTGRES_PASSWORD=benkyoukai
      - POSTGRES_USER=postgres
      - POSTGRES_DB=benkyoukaidb
    volumes:
      - d:/.mydockercomposedata:/var/lib/postgresql/data
    networks:
      - back-tier
    restart: always

networks:
  front-tier:
  back-tier:
