name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.400
      - 
        name: Build with dotnet
        run: dotnet build -c release

      - 
        name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ninjaz/benkyoukai.api
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      

